server:
  port: 8081
  servlet:
    context-path: /api
    
spring:
  application:
    name: product
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      
  jmx:
    enabled: false
    
# datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product
    username: sa
    password: 
  
# h2
  h2:
    console:
      enabled: true
      path: /h2-console